### PR TITLE
Update office-365-management-activity-api-schema.md

### PR DESCRIPTION
**Pull request by vippand**
Adding new upcoming fields within Defender for Office 365 Email Message events (Recordtype 28). Clarification on existing fields like Detection tech and Malware family (and what information to expect from them)

### CODE REVIEW

**Comment by vippand** [comment]
@chrisda would you be able to help with this PR?

**Comment by chrisda** [comment]
@vippand, I cannot; a Merge button is not available to me. Also, it's not a good idea to talk about upcoming things until they're available.

**Comment by vippand** [comment]
@chrisda - who will be able to help make the updates to the Main management API schema article?

**Comment by chrisda** [comment]
@vippand, likely Mark Johnson when he returns.

**Comment by vippand** [comment]
Hi @markjjo I am looking to make some updates to Management API schema for Defender for Office Email Events (RecordType 28)- will you be able to help out with this?

**Comment by vippand** [comment]
> @vippand, likely Mark Johnson when he returns.

Thank you!

**Comment by markjjo** [comment]
@vippand I will review and do a copy edit pass on your updates and then merge to live. I will @ comment you when this is done (no later than tomorrow, March 19)

**Comment by markjjo** [comment]
@vippand PR merged. New content is live. Will you please remember to remove the "upcoming field" tag when these fields are available? Thanks.

https://docs.microsoft.com/en-us/office/office-365-management-api/office-365-management-activity-api-schema#microsoft-defender-for-office-365-and-threat-investigation-and-response-schema

**Comment by vippand** [comment]
> @vippand PR merged. New content is live. Will you please remember to remove the "upcoming field" tag when these fields are available? Thanks.
> 
> https://docs.microsoft.com/en-us/office/office-365-management-api/office-365-management-activity-api-schema#microsoft-defender-for-office-365-and-threat-investigation-and-response-schema

Thanks and Ack @markjjo  - We have sent out the MC post, and plan to rollout sometime in April. I will go ahead, and removing the upcoming tags, as soon as we begin roll out.

**Pull request merged**
