### PR TITLE
Created new O365 activity managemant activity FAQ topic and linked to it from TOC and index

### PR DESCRIPTION
**Pull request by markjjo**
Hi Linda, if no editing issues, can you please go ahead and merge this to live branch? We are ready to publish it. Thanks!

### CODE REVIEW

**Comment by nivnar** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[office-365-management-api/TOC.md](https://github.com/MicrosoftDocs/office-365-management-api/blob/markjjo-working-o365API/office-365-management-api/TOC.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/office/office-365-management-api/office-365-management-activity-api-faq?branch=pr-en-us-23) |
[office-365-management-api/index.md](https://github.com/MicrosoftDocs/office-365-management-api/blob/markjjo-working-o365API/office-365-management-api/index.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/office/office-365-management-api/index?branch=pr-en-us-23) |
[office-365-management-api/office-365-management-activity-api-faq.md](https://github.com/MicrosoftDocs/office-365-management-api/blob/markjjo-working-o365API/office-365-management-api/office-365-management-activity-api-faq.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/office/office-365-management-api/office-365-management-activity-api-faq?branch=pr-en-us-23) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C9%5C20%5C5bf2d4aa-8241-3e63-8951-f50a5c143d97%5CPullRequest%5C201809202205450203-23%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=O2BG%2B8DFQGfNPIkSAbB805ztHQxBrbnZirmZRxeAr%2Fk%3D&st=2018-09-20T22%3A01%3A45Z&se=2018-10-21T22%3A06%3A45Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by Linda-Editor** [comment]
@markjjo  Okay, I'll take a look.

**Comment by markjjo** [comment]
Thanks Linda!

Any change you could change the 1st FAQ:

From this: Where can I see what all events are captured for a specific Office 365 service?

To this: What events are audited for a specific Office 365 service?

If the topic as to come back to me to address an editing issue, I can make the change. But if you publish, it would be great if you could make this change. Not a showstopper.

Mark

**Comment by Linda-Editor** [comment]
Got it. Here are the changes in master: https://review.docs.microsoft.com/en-us/office/office-365-management-api/office-365-management-activity-api-faq?branch=master

Let me know if it looks good, and I'll merge the changes to live.

**Comment by markjjo** [comment]
That looks great! Please merge changes to live. Thanks again for your help.

**Pull request merged**
