### PR TITLE
Update office-365-management-activity-api-schema.md

### PR DESCRIPTION
**Pull request by malhotrasumit**
Updates for ATP P1 and ATP P2 SKU and Service Plans changes.

### CODE REVIEW

**Comment by nivnar** [comment]
OPS Build status updates of commit _[9c5c917](https://github.com/malhotrasumit/office-365-management-api/pull/70/commits/9c5c917021806ef70cdf9bf36fb8335923c50538)_: 

:clock10: **Preparing**: average preparing time is _47 sec(s)_

**Comment by nivnar** [comment]
OPS Build status updates of commit _[9c5c917](https://github.com/malhotrasumit/office-365-management-api/pull/70/commits/9c5c917021806ef70cdf9bf36fb8335923c50538)_: 

:clock10: **Incremental building**: average incremental building time is _19 sec(s)_

**Comment by nivnar** [comment]
OPS Build status updates of commit _[9c5c917](https://github.com/malhotrasumit/office-365-management-api/pull/70/commits/9c5c917021806ef70cdf9bf36fb8335923c50538)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[office-365-management-api/office-365-management-activity-api-schema.md](https://github.com/malhotrasumit/office-365-management-api/blob/patch-7/office-365-management-api/office-365-management-activity-api-schema.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/office/office-365-management-api/office-365-management-activity-api-schema?branch=pr-en-us-70) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C3%5C11%5C5bf2d4aa-8241-3e63-8951-f50a5c143d97%5CPullRequest%5C201903110404015823-70%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=fUnwUhZ%2F43OZxvhNlpW%2F%2FHKiETLVNlRlDRnfkms4jo4%3D&st=2019-03-11T04%3A00%3A05Z&se=2019-04-11T04%3A05%3A05Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by markjjo** [comment]
@malhotrasumit Are you ready to publish these changes to the live site?

**Comment by malhotrasumit** [comment]
Hi Mark, we’re moving away from using “Threat Intelligence” as a term with the ATP P2 SKU now. I just want to make sure the changes I made don’t break the bookmark for that part of the schema. I wasn’t able to fix that in my updates. If that works, we are ready to go.

+@Denise Vangel<mailto:Denise.Vangel@microsoft.com>

**Comment by markjjo** [comment]
@malhotrasumit Thanks for quick response. I will verify/fix the bookmarks and then publish.

**Comment by malhotrasumit** [comment]
This should be fine, Sumit and Mark.

Denise Vangel (deniseb)
425-707-1403

From: Sumit Malhotra <sumitm@microsoft.com>
Sent: Tuesday, March 12, 2019 10:19 AM
To: MicrosoftDocs/office-365-management-api <reply@reply.github.com>; MicrosoftDocs/office-365-management-api <office-365-management-api@noreply.github.com>; Denise Vangel <Denise.Vangel@microsoft.com>
Cc: Mention <mention@noreply.github.com>
Subject: RE: [MicrosoftDocs/office-365-management-api] Update office-365-management-activity-api-schema.md (#70)

Hi Mark, we're moving away from using "Threat Intelligence" as a term with the ATP P2 SKU now. I just want to make sure the changes I made don't break the bookmark for that part of the schema. I wasn't able to fix that in my updates. If that works, we are ready to go.

+@Denise Vangel<mailto:Denise.Vangel@microsoft.com>

**Pull request merged**
