### PR TITLE
update-cpm-schema-missing-fields

### PR DESCRIPTION
**Pull request by vbhatt0211**
Submitted via Learn Editor.

### CODE REVIEW

**Comment by vbhatt0211** [comment]
@lindalu-MSFT : Could you please help on this?

**Comment by lindalu-MSFT** [comment]
@vbhatt0211 Please remove or correct the bookmarks at line 66 & 67 and add a space after the table at line 2254. When you commit the changes, that will kick off a new build. If it returns with no warnings, then I will merge and publish. Thanks, Linda

**Comment by joagarwal** [comment]
@vbhatt0211  @lindalu-MSFT  Please remove the changes for Data connectors here. I had raised a revert PR and these changes went live because of this merge and are incorrect.

**Comment by vbhatt0211** [comment]
Already done and fixed errors in the new PR https://github.com/MicrosoftDocs/office-365-management-api/pull/448

THANKS
VAISHALI
________________________________

**Pull request merged**
