### PR TITLE
Link 2 blogs to this article please

### PR DESCRIPTION
**Pull request by walidelmorsy**
Mas Libman (PG) has asked me to link the 2 blogs we wrote late last year as a reference to this article. Similar to what we have here (https://learn.microsoft.com/en-us/microsoft-365/compliance/sensitivity-labels-office-apps?view=o365-worldwide#auditing-labeling-activities). those two blogs became very popular, and they are being referenced by PG in many conversations. I didn't want to place the reference awkwardly, so I think you are the best team to decide where in the doc to place it

### CODE REVIEW

**Comment by lindalu-MSFT** [comment]
@walidelmorsy I'm not sure what you want me to do here or what blogs you're referring to.

**Comment by walidelmorsy** [comment]
@lindalu-MSFT could we please reference both of these blogs (https://techcommunity.microsoft.com/t5/security-compliance-and-identity/microsoft-365-compliance-audit-log-activities-via-o365/ba-p/2957171) and (https://techcommunity.microsoft.com/t5/security-compliance-and-identity/microsoft-365-compliance-audit-log-activities-via-o365/ba-p/2957297) in this article please similar to what was done in (https://learn.microsoft.com/en-us/microsoft-365/compliance/sensitivity-labels-office-apps?view=o365-worldwide#auditing-labeling-activities)?

**Comment by lindalu-MSFT** [comment]
RIght, you want me to add the Tip to another article, right? Which article?

**Comment by walidelmorsy** [comment]
This one please (https://learn.microsoft.com/en-au/office/office-365-management-api/office-365-management-activity-api-reference)

**Comment by lindalu-MSFT** [comment]
Hi, fixed in a different PR. See https://github.com/MicrosoftDocs/office-365-management-api/pull/321.

**Pull request closed without merging**
