### PR TITLE
Removing SLA time for increasing throttling limit

### PR DESCRIPTION
**Pull request by muralinat**
Removing SLA time for increasing throttling limit per PMs ask

### CODE REVIEW

**Comment by nivnar** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[office-365-management-api/office-365-management-activity-api-faq.md](https://github.com/muralinat/office-365-management-api/blob/patch-3/office-365-management-api/office-365-management-activity-api-faq.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/office/office-365-management-api/office-365-management-activity-api-faq?branch=pr-en-us-25) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C9%5C24%5C5bf2d4aa-8241-3e63-8951-f50a5c143d97%5CPullRequest%5C201809241429112617-25%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=7jrlEW9mhknZunm0fbbNWiuqAJnJ9pkh9xL6Lcfu1bo%3D&st=2018-09-24T14%3A25%3A12Z&se=2018-10-25T14%3A30%3A12Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by nivnar** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[office-365-management-api/office-365-management-activity-api-faq.md](https://github.com/muralinat/office-365-management-api/blob/patch-3/office-365-management-api/office-365-management-activity-api-faq.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/office/office-365-management-api/office-365-management-activity-api-faq?branch=pr-en-us-25) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C9%5C24%5C5bf2d4aa-8241-3e63-8951-f50a5c143d97%5CPullRequest%5C201809241511026513-25%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=ggSKc7HurIB1TbHsdGytjCpdUkr9x4NudKRec%2F%2BHqGQ%3D&st=2018-09-24T15%3A07%3A04Z&se=2018-10-25T15%3A12%3A04Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by Linda-Editor** [comment]
Changes are now live: https://docs.microsoft.com/en-us/office/office-365-management-api/office-365-management-activity-api-faq

**Comment by Linda-Editor** [comment]
@muralinat Thanks for your contribution. In the future, please request a PR to MASTER, not LIVE. We will merge to master, and then live. If you skip this step, master gets out of sync with live and will cause merge conflicts down the line.

cc: @markjjo

**Pull request merged**
