### PR TITLE
Update office-365-management-activity-api-schema.md

### PR DESCRIPTION
**Pull request by malhotrasumit**
Updates for URL time of click events in the ATP/Threat Intelligence schema.

### CODE REVIEW

**Comment by nivnar** [comment]
OPS Build status updates of commit _[0bc7771](https://github.com/malhotrasumit/office-365-management-api/pull/64/commits/0bc777141c28b64eb881173e642edac4a5248881)_: 

:clock10: **Preparing**: average preparing time is _49 sec(s)_

**Comment by nivnar** [comment]
OPS Build status updates of commit _[0bc7771](https://github.com/malhotrasumit/office-365-management-api/pull/64/commits/0bc777141c28b64eb881173e642edac4a5248881)_: 

:clock10: **Incremental building**: average incremental building time is _19 sec(s)_

**Comment by nivnar** [comment]
OPS Build status updates of commit _[0bc7771](https://github.com/malhotrasumit/office-365-management-api/pull/64/commits/0bc777141c28b64eb881173e642edac4a5248881)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[office-365-management-api/office-365-management-activity-api-schema.md](https://github.com/malhotrasumit/office-365-management-api/blob/patch-6/office-365-management-api/office-365-management-activity-api-schema.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/office/office-365-management-api/office-365-management-activity-api-schema?branch=pr-en-us-64) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C3%5C4%5C5bf2d4aa-8241-3e63-8951-f50a5c143d97%5CPullRequest%5C201903042345538203-64%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=3eMAb3ocEDdQrYdTuBqIq7chX8t%2BO3HrJ4DhvDHkfuA%3D&st=2019-03-04T23%3A41%3A56Z&se=2019-04-04T23%3A46%3A56Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by nivnar** [comment]
OPS Build status updates of commit _[94250ff](https://github.com/malhotrasumit/office-365-management-api/pull/64/commits/94250ff00fb8f0f31f8c7e479c78c32e25542561)_: 

:clock10: **Preparing**: average preparing time is _48 sec(s)_

**Comment by nivnar** [comment]
OPS Build status updates of commit _[94250ff](https://github.com/malhotrasumit/office-365-management-api/pull/64/commits/94250ff00fb8f0f31f8c7e479c78c32e25542561)_: 

:clock10: **Incremental building**: average incremental building time is _19 sec(s)_

**Comment by nivnar** [comment]
OPS Build status updates of commit _[94250ff](https://github.com/malhotrasumit/office-365-management-api/pull/64/commits/94250ff00fb8f0f31f8c7e479c78c32e25542561)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[office-365-management-api/office-365-management-activity-api-schema.md](https://github.com/malhotrasumit/office-365-management-api/blob/patch-6/office-365-management-api/office-365-management-activity-api-schema.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/office/office-365-management-api/office-365-management-activity-api-schema?branch=pr-en-us-64) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C3%5C5%5C5bf2d4aa-8241-3e63-8951-f50a5c143d97%5CPullRequest%5C201903051731193101-64%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=2ncsttOq1Aeni4KT6fWm3PrR%2F%2BrbArh3Y3B732%2FTRmo%3D&st=2019-03-05T17%3A27%3A21Z&se=2019-04-05T17%3A32%3A21Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by markjjo** [comment]
@malhotrasumit Pull request merged to live

**Pull request merged**
